#!/bin/sh

rm *.tar.gz

./distclean
cpansign sign
perl Makefile.PL
make dist

pod2html JDockApp.pm > JDockApp.html

ssh voltar.org "(cd /home/dillhome/voltar/html/PerlModules; rm Wharf*.gz)"
scp JDockApp.html *.tar.gz voltar.org:/home/dillhome/voltar/html/PerlModules
ssh voltar.org "(cd /home/dillhome/voltar/html/PerlModules; chmod 644 Wharf*.gz JD*.html )"

rm JDockApp.html
